### ISSUE TITLE
Drum Zombie Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Mrbysco/InstrumentalMobs#10]
## Client Info
* `Minecraft v1.16.4`
* `Forge v35.1.13`
* `Instrumental Mobs v1.3.0`
* `Java v8`

## Issue Description
- While spawning in the mobs using the spawn eggs, my server crashed.

## Reproduce Steps
1. Spawn instrumental mobs
2. Crash

## Additional Information
- [Crash Report](https://gist.github.com/WenXin20/a6b9aa7d80b39f1725423d6be8ad0796)

**Comment by Mrbysco** [comment]
Should be fixed next release

**Comment by Mrbysco** [comment]
https://www.curseforge.com/minecraft/mc-mods/instrumental-mobs/files/3146144
