### ISSUE TITLE
Incorrect French Horn Creeper Spawn Egg Name

### ISSUE THREAD

**Issue by MarioMario24680** [Mrbysco/InstrumentalMobs#11]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

## SUGGESTION INFORMATION

Hi, I noticed a small weird issue with the spawn egg for the French Horn Creeper using its ID as its name instead of being "French Horn Creeper Spawn Egg". Here's a screenshot of the item: https://prnt.sc/wa1pti It's not that big of a deal, but it would be appreciated if you could fix it in a minor update.

**Comment by Mrbysco** [comment]
Whoops... I thought I fixed all the names... Thank you for making me aware.
