### ISSUE TITLE
[Bug]: Microphone causes players to crash when used against them

### ISSUE THREAD

**Issue by kcseb** [Mrbysco/InstrumentalMobs#13]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.2.1

### Minecraft version

1.18.2

### Mod version

1.3.4

### Java version

JDK 18.0.2.1

### Issue Description

When using the microphone against a player the person who was attacked will crash. This happens consistently to the two different persons I tried this on. It seems to happen more often when the person who has the microphone used against them, is moving. When stationary, it does not seem to occur anywhere near as much. 

Person 1 is running Arch Linux (Kernel 6.2.6.)
Person 2  is running Windows 10 (Build 21H2) - [Crash Log](https://pastebin.com/D7nXTQ1E)
I am running Windows 10 (Build 21H2) - [Crash Log](https://pastebin.com/5Pburyii)

This issue does not occur with the cymbals, xylophone, drums, or tuba. 
Video of the bug occurring in real-time -> [HERE](https://youtu.be/aJ9DQfZJivc)

**Comment by Mrbysco** [comment]
A new version has been uploaded that should fix this issue
