### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joel4848** [Mrbysco/InstrumentalMobs#14]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the mod

### Forge version

40.2.1

### Minecraft version

1.18.2

### Mod version

1.3.5

### Java version

17

### Issue Description

Xylophones still drop despite instrumentDropChance = 0.0 (no other instruments drop - just xylophones)

**Comment by Mrbysco** [comment]
Have you restarted and had new mobs spawn after changing the config?

**Comment by joel4848** [comment]
Yes. The config change clearly has some effect as it stops all other instruments dropping apart from xylophones.

**Comment by Mrbysco** [comment]
A fix is being uploaded

**Comment by joel4848** [comment]
Incredible, thank you
