### ISSUE TITLE
[Bug]: New Trumpet Skeleton mob drops Xylophone instead

### ISSUE THREAD

**Issue by dandalous** [Mrbysco/InstrumentalMobs#15]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.0

### Minecraft version

1.20.1

### Mod version

2.1.1

### Java version

Java 17 update 8

### Issue Description

New Trumpet Skeleton mob drops Xylophone instead.

(Also thanks for adding the Trumpet Skeleton!)

### Additional Information

Configuration:
Instrument Drop Chance: 0.05
Instrument Hurt Chance: 0.3 (default)
Instrument Range: 10.0 (default)
Mobs React: On (default)
Sound Damage Chance: 0.35 (default)

**Comment by Mrbysco** [comment]
Fixed next release
