### ISSUE TITLE
Instrumental mobs crashed the nether

### ISSUE THREAD

**Issue by aaronhowser1** [Mrbysco/InstrumentalMobs#6]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.5.2838 
* Mod Version: 1.1
* Java Version: 1.8.0_51

## Issue Description
/FTBTeam/FTB-Academy/issues/12
https://paste.feed-the-beast.com/view/9bee48eb

**Comment by Mrbysco** [comment]
New version has been uploaded that should fix the issue,
Could you please try again with the new version (1.2)
https://www.curseforge.com/minecraft/mc-mods/instrumental-mobs/files/2767795

**Comment by aaronhowser1** [comment]
It wasnt me that had the crash, but a player in my modpack. They didn't get back to me, but someone else had the same issue and they said that updating the mod fixed it for them.
